name: PyInstaller Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        venv\Scripts\activate
      shell: pwsh

    - name: Upgrade pip
      run: |
        venv\Scripts\python -m pip install --upgrade pip
      shell: pwsh

    - name: Install dependencies
      run: |
        venv\Scripts\python -m pip install -r requirements.txt
      shell: pwsh

    - name: Build with PyInstaller
      run: |
        venv\Scripts\python -m pyinstaller --onefile pyinstaller.spec
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
